// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hscgtzzoyzuhceibvqtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzY2d0enpveXp1aGNlaWJ2cXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3ODA3MDAsImV4cCI6MjA3MDM1NjcwMH0.VEpTu3i8g-cAuWdZ8WiFcm9-TJ1zP-W3qJy01qUUSQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});